// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/k8s"
	v1 "k8s.io/api/core/v1"
)

type K8sConfigMapDeployer struct {
	DeployStub        func(context.Context, v1.ConfigMap) error
	deployMutex       sync.RWMutex
	deployArgsForCall []struct {
		arg1 context.Context
		arg2 v1.ConfigMap
	}
	deployReturns struct {
		result1 error
	}
	deployReturnsOnCall map[int]struct {
		result1 error
	}
	GetStub        func(context.Context, k8s.Namespace, string) (*v1.ConfigMap, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 k8s.Namespace
		arg3 string
	}
	getReturns struct {
		result1 *v1.ConfigMap
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *v1.ConfigMap
		result2 error
	}
	UndeployStub        func(context.Context, k8s.Namespace, string) error
	undeployMutex       sync.RWMutex
	undeployArgsForCall []struct {
		arg1 context.Context
		arg2 k8s.Namespace
		arg3 string
	}
	undeployReturns struct {
		result1 error
	}
	undeployReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *K8sConfigMapDeployer) Deploy(arg1 context.Context, arg2 v1.ConfigMap) error {
	fake.deployMutex.Lock()
	ret, specificReturn := fake.deployReturnsOnCall[len(fake.deployArgsForCall)]
	fake.deployArgsForCall = append(fake.deployArgsForCall, struct {
		arg1 context.Context
		arg2 v1.ConfigMap
	}{arg1, arg2})
	stub := fake.DeployStub
	fakeReturns := fake.deployReturns
	fake.recordInvocation("Deploy", []interface{}{arg1, arg2})
	fake.deployMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *K8sConfigMapDeployer) DeployCallCount() int {
	fake.deployMutex.RLock()
	defer fake.deployMutex.RUnlock()
	return len(fake.deployArgsForCall)
}

func (fake *K8sConfigMapDeployer) DeployCalls(stub func(context.Context, v1.ConfigMap) error) {
	fake.deployMutex.Lock()
	defer fake.deployMutex.Unlock()
	fake.DeployStub = stub
}

func (fake *K8sConfigMapDeployer) DeployArgsForCall(i int) (context.Context, v1.ConfigMap) {
	fake.deployMutex.RLock()
	defer fake.deployMutex.RUnlock()
	argsForCall := fake.deployArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *K8sConfigMapDeployer) DeployReturns(result1 error) {
	fake.deployMutex.Lock()
	defer fake.deployMutex.Unlock()
	fake.DeployStub = nil
	fake.deployReturns = struct {
		result1 error
	}{result1}
}

func (fake *K8sConfigMapDeployer) DeployReturnsOnCall(i int, result1 error) {
	fake.deployMutex.Lock()
	defer fake.deployMutex.Unlock()
	fake.DeployStub = nil
	if fake.deployReturnsOnCall == nil {
		fake.deployReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deployReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *K8sConfigMapDeployer) Get(arg1 context.Context, arg2 k8s.Namespace, arg3 string) (*v1.ConfigMap, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 k8s.Namespace
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2, arg3})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *K8sConfigMapDeployer) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *K8sConfigMapDeployer) GetCalls(stub func(context.Context, k8s.Namespace, string) (*v1.ConfigMap, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *K8sConfigMapDeployer) GetArgsForCall(i int) (context.Context, k8s.Namespace, string) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *K8sConfigMapDeployer) GetReturns(result1 *v1.ConfigMap, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *v1.ConfigMap
		result2 error
	}{result1, result2}
}

func (fake *K8sConfigMapDeployer) GetReturnsOnCall(i int, result1 *v1.ConfigMap, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *v1.ConfigMap
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *v1.ConfigMap
		result2 error
	}{result1, result2}
}

func (fake *K8sConfigMapDeployer) Undeploy(arg1 context.Context, arg2 k8s.Namespace, arg3 string) error {
	fake.undeployMutex.Lock()
	ret, specificReturn := fake.undeployReturnsOnCall[len(fake.undeployArgsForCall)]
	fake.undeployArgsForCall = append(fake.undeployArgsForCall, struct {
		arg1 context.Context
		arg2 k8s.Namespace
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.UndeployStub
	fakeReturns := fake.undeployReturns
	fake.recordInvocation("Undeploy", []interface{}{arg1, arg2, arg3})
	fake.undeployMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *K8sConfigMapDeployer) UndeployCallCount() int {
	fake.undeployMutex.RLock()
	defer fake.undeployMutex.RUnlock()
	return len(fake.undeployArgsForCall)
}

func (fake *K8sConfigMapDeployer) UndeployCalls(stub func(context.Context, k8s.Namespace, string) error) {
	fake.undeployMutex.Lock()
	defer fake.undeployMutex.Unlock()
	fake.UndeployStub = stub
}

func (fake *K8sConfigMapDeployer) UndeployArgsForCall(i int) (context.Context, k8s.Namespace, string) {
	fake.undeployMutex.RLock()
	defer fake.undeployMutex.RUnlock()
	argsForCall := fake.undeployArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *K8sConfigMapDeployer) UndeployReturns(result1 error) {
	fake.undeployMutex.Lock()
	defer fake.undeployMutex.Unlock()
	fake.UndeployStub = nil
	fake.undeployReturns = struct {
		result1 error
	}{result1}
}

func (fake *K8sConfigMapDeployer) UndeployReturnsOnCall(i int, result1 error) {
	fake.undeployMutex.Lock()
	defer fake.undeployMutex.Unlock()
	fake.UndeployStub = nil
	if fake.undeployReturnsOnCall == nil {
		fake.undeployReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.undeployReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *K8sConfigMapDeployer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deployMutex.RLock()
	defer fake.deployMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.undeployMutex.RLock()
	defer fake.undeployMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *K8sConfigMapDeployer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ k8s.ConfigMapDeployer = new(K8sConfigMapDeployer)
